using Microsoft.Xna.Framework;
using System.Collections.Generic;
using System;
using Terraria;
using Terraria.ID;
using Terraria.Localization;
using Terraria.ModLoader;
using RagnarokMod.Utils;
using CalamityMod;
using CalamityMod.NPCs;
using ThoriumMod;
using ThoriumMod.NPCs;


namespace RagnarokMod.Common.GlobalNPCs
{
    public class AddEnemyVulnerabilities : GlobalNPC
    {
		private static Mod thorium = ModLoader.GetMod("ThoriumMod");
		public override bool AppliesToEntity(NPC npc, bool lateInstantiation)
        {
			foreach (var entry in npcNames) 
			{
				if ( npc.type == thorium.Find<ModNPC>(entry).Type ) 
				{
					return true;
				}
			}
			return false;
		}
	
		//private static Dictionary<int, int> thoriumNPCTypetoInteger;
		
		/*
		public override void Load()
		{
			thoriumNPCTypetoInteger = new Dictionary<int, int>();
			foreach (var entry in thorium_damage_tweak)
			{
				int enemytype = (thorium.Find<ModNPC>(entry.Key)).Type;
				thoriumNPCTypetoInteger[enemytype] = entry.Value;
			}
		}
		*/
		private static List<string> npcNames = new List<string> 
		{	
			"TheGrandThunderBirdv2",
			"Viscount",
			"QueenJelly",
			"GraniteEnergyStorm",
			"TheBuriedWarrior",
			"ThePrimeScouter",
			"BoreanStrider",
			"BoreanStriderPopped",
			"FallenDeathBeholder",
			"FallenDeathBeholder2",
			"Lich",
			"LichHeadless",
			"Abyssion",
			"AbyssionCracked",
			"AbyssionReleased",
			"Omnicide",
			"RealityBreaker",
			"ViscountBaby",
			"Hatchling",
			"ZealousJelly",
			"DistractJelly",
			"SpittingJelly",
			"GraniteEnergy",
			"EncroachingEnergy",
			"EnergyStormConduit",
			"PyroCore",
			"CryoCore",
			"BioCore",
			"BoreanMyte1",
			"BoreanHopper",
			"ThousandSoulPhalactry",
			"AbyssalSpawn",
			"CorpseBloom",
			"CorpsePetal",
			"CorpseWeed",
			"Illusionist",
			"IllusionistDecoy",
			"PatchWerk",
			"Maggot",
			"BurstingMaggot",
			"AncientArcher",
			"AncientCharger",
			"AncientPhalanx",
			"ArmyAnt",
			"FireAnt",
			"BabySpider",
			"BigBone",
			"Biter",
			"BizarreRockFormation",
			"Blowfish",
			"LivingHemorrhage",
			"Clot",
			"Coolmera",
			"DarksteelKnight",
			"EarthenBat",
			"EarthenGolem",
			"FrostWurmHead",
			"FrostWurmBody1",
			"FrostWurmBody2",
			"FrostWurmTail",
			"FrozenFace",
			"GelatinousCube",
			"GigaClam",
			"GildedLycan",
			"GraniteEradicator",
			"GraniteFusedSlime",
			"GraniteSurger",
			"GreenHag",
			"CyanHag",
			"Hammerhead",
			"HoppingSpider",
			"LifeCrystalMimic",
			"ManofWar",
			"BloomMahoganyEnt",
			"MahoganyEnt",
			"MorayHead",
			"MorayBody",
			"MorayTail",
			"MudMan",
			"Nestling",
			"Octopus",
			"RagingMinotaur",
			"Shambler",
			"GelatinousSludge",
			"SnowBall",
			"SnowEater",
			"SpaceSlime",
			"StrangeBulb",
			"TheInnocent",
			"UFO",
			"UnstableEnergyAnomaly",
			"WindElemental",
			"AbyssalAngler",
			"AstroBeetle",
			"BlackWidow",
			"BrownRecluse",
			"BrownRecluseBaby",
			"Blister",
			"BlisterPod",
			"BoneFlayer",
			"ChilledSpitter",
			"Coldling",
			"CrownofThorns",
			"DissonanceSeer",
			"EpiDermon",
			"FeedingFrenzy",
			"Freezer",
			"FrostFang",
			"FrozenGross",
			"GlitteringGolem",
			"HorrificCharger",
			"HellBringerMimic",
			"InfernalHound",
			"Lycan",
			"LihzardMimic",
			"LihzardPotMimic1",
			"LihzardPotMimic2",
			"MartianScout",
			"MartianSentry",
			"MossWasp",
			"MyceliumMimic",
			"NecroPot",
			"PutridSerpent",
			"SnowFlinxMatriarch",
			"SoulCorrupter",
			"Spectrumite",
			"SubmergedMimic",
			"SunPriestess",
			"Tarantula",
			"TheStarved",
			"Whale",
			"UnderworldPot1",
			"UnderworldPot2",
			"VampireSquid",
			"VileFloater",
			"VoltEelHead",
			"VoltEelBody1",
			"VoltEelBody2",
			"VoltEelTail",
			"BloodDrop",
			"BloodMage",
			"BloodyWarg",
			"EngorgedEye",
			"SeveredLegs",
			"SmotheringShade",
			"SnowElemental",
			"GoblinDrummer",
			"GoblinTrapper",
			"GoblinSpiritGuide",
			"ShadowflameRevenant",
			"SeaShantySinger",
			"LeFantome",
			"ScissorStalker",
			"SnowSinga",
			"SnowyOwl",
			"Blobfish",
			"BlizzardBat",
			"FrostBurnt",
			"FrostBurntFlayer",
			"Kraken",
			"GildedSlime",
			"GildedSlimeling",
			"Abomination",
			"Sharptooth",
			"BlueHag",
			"RedHag",
			"Barracuda",
			"FlamekinCaster",
			"GildedBat",
			"GraveLimb",
			"Globee",
			"MoltenMortar"
		};
		
		private static Dictionary<string,bool> thorium_npc_debuff_cold_vulnerability = new Dictionary<string,bool>
		{
			// If value is 1, the npc is vulnerable, 0 is resistance and no entry is neutral
			// Bosses and minions
			{"TheGrandThunderBirdv2", true},
			{"QueenJelly", true},
			{"ZealousJelly", true},
			{"DistractJelly", true},
			{"SpittingJelly", true},
			{"TheBuriedWarrior", true},
			{"GraniteEnergyStorm", true},
			{"ThePrimeScouter", false},
			{"BoreanStrider", false},
			{"BoreanStriderPopped", false},
			{"FallenDeathBeholder", false},
			{"FallenDeathBeholder2", false},
			{"Abyssion", false},
			{"AbyssionCracked", false},
			{"Hatchling", true},
			{"GraniteEnergy", true},
			{"EncroachingEnergy", true},
			{"EnergyStormConduit", true},
			{"CryoCore", false},
			{"BoreanMyte1", false},
			{"BoreanHopper", false},
			{"EnemyBeholder", false},
			{"CorpseBloom", true},
			{"CorpsePetal", true},
			{"CorpseWeed", true},
			// All other NPCs
			{"AncientArcher", true},
			{"AncientCharger", true},
			{"AncientPhalanx", true},
			{"ArmyAnt", true},
			{"Biter", true},
			{"BizarreRockFormation", true},
			{"Blowfish", true},
			{"LivingHemorrhage", true},
			{"Clot", true},
			{"Coolmera", false},
			{"EarthenBat", true},
			{"EarthenGolem", true},
			{"FrostWurmHead", false},
			{"FrostWurmBody1", false},
			{"FrostWurmBody2", false},
			{"FrostWurmTail", false},
			{"FrozenFace", false},
			{"GildedBat", true},
			{"GraniteEradicator", true},
			{"GraniteFusedSlime", true},
			{"GraniteSurger", true},
			{"CyanHag", false},
			{"LifeCrystalMimic", true},
			{"BloomMahoganyEnt", true},
			{"MahoganyEnt", true},
			{"Nestling", false},
			{"SnowBall",  false},
			{"SnowEater", false},
			{"SpaceSlime", true},
			{"StrangeBulb", true},
			{"TheInnocent", true},
			{"UFO", false},
			{"UnstableEnergyAnomaly", true},
			{"BlackWidow", true},
			{"BrownRecluse", true},
			{"BrownRecluseBaby", true},
			{"Blister", true},
			{"BlisterPod", true},
			{"BoneFlayer", true},
			{"ChilledSpitter", false},
			{"Coldling", false},
			{"DissonanceSeer", true},
			{"Freezer", false},
			{"FrostFang", false},
			{"FrozenGross", false},
			{"GlitteringGolem", true},
			{"HorrificCharger", true},
			{"Lycan", true},
			{"MartianScout", false},
			{"MoltenMortar", true},
			{"MossWasp", true},
			{"SnowFlinxMatriarch", false},
			{"SoulCorrupter", true},
			{"Spectrumite", true},
			{"Tarantula", true},
			{"TheStarved", true},
			{"UnderworldPot1", true},
			{"UnderworldPot2", true},
			{"VileFloater", true},
			{"Abomination", true},
			{"BloodMage", true},
			{"BloodyWarg", true},
			{"EngorgedEye", true},
			{"GraveLimb", true},
			{"SeveredLegs", true},
			{"SmotheringShade", true},
			{"BlizzardBat", false},
			{"FrostBurnt", false},
			{"FrostBurntFlayer", false},
			{"SnowElemental", false},
			{"SnowyOwl", false},
			{"GoblinSpiritGuide", true},
			{"SeaShantySinger", true},
			{"LeFantome", true},
			{"ScissorStalker", true},
			{"SnowSinga", false}
		};
		
		private static Dictionary<string,bool> thorium_npc_debuff_water_vulnerability = new Dictionary<string,bool>
		{
			// If value is 1, the npc is vulnerable, 0 is resistance and no entry is neutral
			// Bosses and minions
			{"QueenJelly", false},
			{"GraniteEnergyStorm", true},
			{"ThePrimeScouter", true},
			{"BoreanStrider", false},
			{"BoreanStriderPopped", false},
			{"FallenDeathBeholder", true},
			{"FallenDeathBeholder2", true},
			{"Abyssion", false},
			{"AbyssionCracked", false},
			{"AbyssionReleased", false},
			{"RealityBreaker", false},
			{"SlagFury", true},
			{"Aquaius", false},
			{"ZealousJelly", false},
			{"DistractJelly", false},
			{"SpittingJelly", false},
			{"EncroachingEnergy", true},
			{"PyroCore", true},
			{"BoreanMyte1", false},
			{"BoreanHopper", false},
			{"EnemyBeholder", true},
			{"AbyssalSpawn", false},
			{"AquaiusBubble", false},
			{"LucidBubble", false},
			{"CorpseBloom", false},
			{"CorpsePetal", false},
			{"CorpseWeed", false},
			// All other NPCs
			{"FireAnt", true},
			{"Barracuda", false},
			{"BatOutaHell", true},
			{"FlamekinCaster", true},
			{"Blowfish", false},
			{"GigaClam", false},
			{"BigBone", true},
			{"Globee", false},
			{"GraniteEradicator", true},
			{"GraniteSurger", true},
			{"BlueHag", false},
			{"RedHag", true},
			{"Hammerhead", false},
			{"LifeCrystalMimic", true},
			{"ManofWar", false},
			{"BloomMahoganyEnt", false},
			{"MahoganyEnt", false},
			{"Octopus", false},
			{"Shambler", true},
			{"Sharptooth", false},
			{"SpaceSlime", true},
			{"StrangeBulb", false},
			{"TheInnocent", false},
			{"UFO", true},
			{"UnstableEnergyAnomaly", true},
			{"AbyssalAngler", false},
			{"AstroBeetle", false},
			{"AquaticHallucination", false},
			{"Blobfish", false},
			{"BoneFlayer", true},
			{"CrownofThorns", false},
			{"EpiDermon", true},
			{"FeedingFrenzy", false},
			{"GlitteringGolem", true},
			{"HellBringerMimic", true},
			{"InfernalHound", true},
			{"Kraken", false},
			{"MoltenMortar", true},
			{"MyceliumMimic", false},
			{"NecroPot", true},
			{"PutridSerpent", false},
			{"SubmergedMimic", false},
			{"Whale", false},
			{"UnderworldPot1", true},
			{"UnderworldPot2", true},
			{"VampireSquid", false},
			{"VoltEelHead", false},
			{"VoltEelBody1", false},
			{"VoltEelBody2", false},
			{"VoltEelTail", false},
			{"BloodDrop", false},
			{"ShadowflameRevenant", true}
		};
		
		private static Dictionary<string,bool> thorium_npc_debuff_sickness_vulnerability = new Dictionary<string,bool>
		{
			// If value is 1, the npc is vulnerable, 0 is resistance and no entry is neutral
			// Bosses and minions
			{"TheGrandThunderBirdv2", true},
			{"Viscount", false},
			{"QueenJelly", false},
			{"GraniteEnergyStorm", false},
			{"TheBuriedWarrior", false},
			{"ThePrimeScouter", false},
			{"BoreanStrider", true},
			{"BoreanStriderPopped", true},
			{"FallenDeathBeholder", false},
			{"FallenDeathBeholder2", false},
			{"Lich", false},
			{"LichHeadless", false},
			{"Abyssion", true},
			{"AbyssionCracked", true},
			{"AbyssionReleased", true},
			{"Omnicide", false},
			{"RealityBreaker", false},
			{"ViscountBaby", false},
			{"Hatchling", true},
			{"ZealousJelly", false},
			{"DistractJelly", false},
			{"SpittingJelly", false},
			{"GraniteEnergy", false},
			{"EncroachingEnergy", false},
			{"EnergyStormConduit", false},
			{"PyroCore", false},
			{"CryoCore", false},
			{"BioCore", false},
			{"BoreanMyte1", true},
			{"BoreanHopper", true},
			{"ThousandSoulPhalactry", false},
			{"AbyssalSpawn", true},
			{"CorpseBloom", true},
			{"CorpsePetal", true},
			{"CorpseWeed", true},
			{"Illusionist", false},
			{"IllusionistDecoy", false},
			{"PatchWerk", false},
			{"Maggot", false},
	     	{"BurstingMaggot", false},
			// All other NPCs
			{"AncientArcher", false},
			{"AncientCharger", false},
			{"AncientPhalanx", false},
			{"ArmyAnt", false},
			{"FireAnt", false},
			{"BigBone", false},
			{"Biter", false},
			{"BizarreRockFormation", false},
			{"Blowfish", false},
			{"LivingHemorrhage", true},
			{"Clot", true},
			{"Coolmera", true},
			{"DarksteelKnight", false},
			{"EarthenBat", false},
			{"EarthenGolem", false},
			{"FrostWurmHead", true},
			{"FrostWurmBody1", true},
			{"FrostWurmBody2", true},
			{"FrostWurmTail", true},
			{"FrozenFace", true},
			{"GelatinousCube", true},
			{"GigaClam", true},
			{"GildedLycan", true},
			{"GraniteEradicator", false},
			{"GraniteFusedSlime", false},
			{"GraniteSurger", false},
			{"GreenHag", false},
			{"CyanHag", true},
			{"Hammerhead", true},
			{"HoppingSpider", false},
			{"LifeCrystalMimic", false},
			{"ManofWar", false},
			{"BloomMahoganyEnt", false},
			{"MahoganyEnt", false},
			{"MorayHead", false},
			{"MorayBody", false},
			{"MorayTail", false},
			{"MudMan", false},
			{"Nestling", true},
			{"Octopus", true},
			{"RagingMinotaur", true},
			{"Shambler", false},
			{"GelatinousSludge", true},
			{"SnowBall",  false},
			{"SnowEater", true},
			{"SpaceSlime", false},
			{"StrangeBulb", false},
			{"TheInnocent", true},
			{"UFO", false},
			{"UnstableEnergyAnomaly", false},
			{"WindElemental", false},
			{"AbyssalAngler", true},
			{"AstroBeetle", false},
			{"BlackWidow", false},
			{"BrownRecluse", false},
			{"BrownRecluseBaby", false},
			{"Blister", true},
			{"BlisterPod", true},
			{"BoneFlayer", false},
			{"ChilledSpitter", true},
			{"Coldling", true},
			{"CrownofThorns", true},
			{"DissonanceSeer", false},
			{"EpiDermon", true},
			{"FeedingFrenzy", true},
			{"Freezer", true},
			{"FrostFang", true},
			{"FrozenGross", true},
			{"GlitteringGolem", false},
			{"HorrificCharger", true},
			{"HellBringerMimic", false},
			{"InfernalHound", true},
			{"Lycan", true},
			{"LihzardMimic", false},
			{"LihzardPotMimic1", false},
			{"LihzardPotMimic2", false},
			{"MartianScout", true},
			{"MartianSentry", false},
			{"MossWasp", false},
			{"MyceliumMimic", false},
			{"NecroPot", false},
			{"PutridSerpent", true},
			{"SnowFlinxMatriarch", true},
			{"SoulCorrupter", true},
			{"Spectrumite", false},
			{"SubmergedMimic", false},
			{"SunPriestess", true},
			{"Tarantula", true},
			{"TheStarved", true},
			{"Whale", true},
			{"UnderworldPot1", false},
			{"UnderworldPot2", false},
			{"VampireSquid", true},
			{"VileFloater", true},
			{"VoltEelHead", true},
			{"VoltEelBody1", true},
			{"VoltEelBody2", true},
			{"VoltEelTail", true},
			{"BloodDrop", true},
			{"BloodMage", true},
			{"BloodyWarg", true},
			{"EngorgedEye", true},
			{"SeveredLegs", true},
			{"SmotheringShade", false},
			{"SnowElemental", false},
			{"GoblinDrummer", true},
			{"GoblinTrapper", true},
			{"GoblinSpiritGuide", true},
			{"ShadowflameRevenant", false},
			{"SeaShantySinger", true},
			{"LeFantome", true},
			{"ScissorStalker", true},
			{"SnowSinga", false}
		};
		
		private static Dictionary<string,bool> thorium_npc_debuff_electricity_vulnerability = new Dictionary<string,bool>
		{
			// If value is 1, the npc is vulnerable, 0 is resistance and no entry is neutral
			// Bosses and minions
			{"TheGrandThunderBirdv2", false},
			{"Viscount", true},
			{"QueenJelly", false},
			{"GraniteEnergyStorm", false},
			{"TheBuriedWarrior", true},
			{"ThePrimeScouter", true},
			{"BoreanStriderPopped", true},
			{"FallenDeathBeholder", true},
			{"FallenDeathBeholder2", true},
			{"Lich", true},
			{"LichHeadless", true},
			{"Abyssion", true},
			{"AbyssionCracked", true},
			{"AbyssionReleased", true},
			{"Aquaius", true},
			{"ViscountBaby", true},
			{"Hatchling", false},
			{"ZealousJelly", false},
			{"DistractJelly", false},
			{"SpittingJelly", false},
			{"GraniteEnergy", false},
			{"EncroachingEnergy", false},
			{"EnergyStormConduit", false},
			{"PyroCore", true},
			{"CryoCore", true},
			{"BioCore", true},
			{"EnemyBeholder", true},
			{"AbyssalSpawn", true},
			{"AquaiusBubble", true},
			{"LucidBubble", true},
			// All other NPCs
			{"AncientArcher", true},
			{"AncientCharger", true},
			{"AncientPhalanx", true},
			{"Barracuda", true},
			{"BigBone", false},
			{"BizarreRockFormation", false},
			{"Blowfish", true},
			{"DarksteelKnight", true},
			{"EarthenBat", false},
			{"EarthenGolem", false},
			{"GelatinousCube", false},
			{"GigaClam", true},
			{"GildedBat", true},
			{"GildedSlime", true},
			{"GildedSlimeling", true},
			{"GildedLycan", true},
			{"Globee", true},
			{"GraniteEradicator", false},
			{"GraniteFusedSlime", false},
			{"GraniteSurger", false},
			{"BlueHag", true},
			{"Hammerhead", true},
			{"ManofWar", false},
			{"MorayHead", true},
			{"MorayBody", true},
			{"MorayTail", true},
			{"Octopus", true},
			{"GelatinousSludge", false},
			{"Sharptooth", true},
			{"UFO", true},
			{"UnstableEnergyAnomaly", false},
			{"WindElemental", false},
			{"AbyssalAngler", true},
			{"AquaticHallucination", true},
			{"Blobfish", true},
			{"CrownofThorns", true},
			{"FeedingFrenzy", true},
			{"GlitteringGolem", false},
			{"Kraken", true},
			{"MartianSentry", true},
			{"MoltenMortar", false},
			{"PutridSerpent", true},
			{"Spectrumite", true},
			{"SubmergedMimic", true},
			{"Whale", true},
			{"VampireSquid", true},
			{"VoltEelHead", false},
			{"VoltEelBody1", false},
			{"VoltEelBody2", false},
			{"VoltEelTail", false}
		};
		
		private static Dictionary<string,bool> thorium_npc_debuff_heat_vulnerability = new Dictionary<string,bool>
		{
			// If value is 1, the npc is vulnerable, 0 is resistance and no entry is neutral
			// Bosses and minions
			{"TheGrandThunderBirdv2", false},
			{"QueenJelly", true},
			{"GraniteEnergyStorm", false},
			{"TheBuriedWarrior", false},
			{"ThePrimeScouter", false},
			{"BoreanStrider", true},
			{"BoreanStriderPopped", true},
			{"FallenDeathBeholder", false},
			{"FallenDeathBeholder2", false},
			{"Abyssion", false},
			{"AbyssionReleased", true},
			{"Omnicide", true},
			{"SlagFury", false},
			{"Hatchling", false},
			{"ZealousJelly", true},
			{"DistractJelly", true},
			{"SpittingJelly", true},
			{"GraniteEnergy", false},
			{"EncroachingEnergy", false},
			{"EnergyStormConduit", false},
			{"PyroCore", false},
			{"CryoCore", true},
			{"BoreanMyte1", true},
			{"BoreanHopper", true},
			{"EnemyBeholder", false},
			{"ThousandSoulPhalactry", false},
			{"LucidBubble", false},
			{"CorpseBloom", true},
			{"CorpsePetal", true},
			{"CorpseWeed", true},
			{"PatchWerk", true},
			{"Maggot", true},
	     	{"BurstingMaggot" , true},
			// All other NPCs
			{"AncientArcher", false},
			{"AncientCharger", false},
			{"AncientPhalanx", false},
			{"ArmyAnt", true},
			{"FireAnt", false},
			{"BabySpider", true},
			{"BatOutaHell", false},
			{"FlamekinCaster", false},
			{"Biter", true},
			{"BizarreRockFormation", false},
			{"LivingHemorrhage", true},
			{"Clot", true},
			{"Coolmera", true},
			{"EarthenBat", true},
			{"EarthenGolem", true},
			{"FrostWurmHead", true},
			{"FrostWurmBody1", true},
			{"FrostWurmBody2", true},
			{"FrostWurmTail", true},
			{"FrozenFace", true},
			{"GelatinousCube", true},
			{"GildedBat", false},
			{"GildedLycan", false},
			{"GraniteEradicator", false},
			{"GraniteSurger", false},
			{"GreenHag", true},
			{"HoppingSpider", true},
			{"LifeCrystalMimic", false},
			{"ManofWar", true},
			{"BloomMahoganyEnt", true},
			{"MahoganyEnt", true},
			{"MudMan", true},
			{"Nestling", true},
			{"RagingMinotaur", false},
			{"GelatinousSludge", true},
			{"SnowBall",  true},
			{"SnowEater", true},
			{"SpaceSlime", false},
			{"StrangeBulb", true},
			{"TheInnocent", true},
			{"UnstableEnergyAnomaly", false},
			{"AstroBeetle", true},
			{"BlackWidow", true},
			{"BrownRecluse", true},
			{"BrownRecluseBaby", true},
			{"Blister", true},
			{"BlisterPod", true},
			{"BoneFlayer", false},
			{"ChilledSpitter", true},
			{"Coldling", true},
			{"DissonanceSeer", true},
			{"EpiDermon", false},
			{"Freezer", true},
			{"FrostFang", true},
			{"FrozenGross", true},
			{"GlitteringGolem", false},
			{"HorrificCharger", true},
			{"HellBringerMimic", false},
			{"InfernalHound", false},
			{"Lycan", true},
			{"MartianScout", true},
			{"MoltenMortar", false},
			{"MossWasp", true},
			{"MyceliumMimic", true},
			{"SnowFlinxMatriarch", true},
			{"Spectrumite", false},
			{"SunPriestess", false},
			{"Tarantula", true},
			{"TheStarved", true},
			{"UnderworldPot1", false},
			{"UnderworldPot2", false},
			{"VileFloater", true},
			{"Abomination", true},
			{"BloodDrop", true},
			{"BloodMage", true},
			{"BloodyWarg", true},
			{"EngorgedEye", true},
			{"GraveLimb", true},
			{"SeveredLegs", true},
			{"SmotheringShade", true},
			{"BlizzardBat", true},
			{"FrostBurnt", true},
			{"FrostBurntFlayer", true},
			{"SnowElemental", true},
			{"SnowyOwl", true},
			{"GoblinSpiritGuide", true},
			{"ShadowflameRevenant", false},
			{"SeaShantySinger", true},
			{"LeFantome", true},
			{"ScissorStalker", true},
			{"SnowSinga", true}
		};
				
		public override void SetDefaults(NPC npc) {	
		//Apply cold vulnerabilities
			foreach (var mob in thorium_npc_debuff_cold_vulnerability) 
			{
				if ( npc.type == thorium.Find<ModNPC>(mob.Key).Type ) 
				{
						npc.Calamity().VulnerableToCold = new bool?(mob.Value);
						break;
				}
			}
			
			//Apply water vulnerabilities
			foreach (var mob in thorium_npc_debuff_water_vulnerability) 
			{
				if ( npc.type == thorium.Find<ModNPC>(mob.Key).Type ) 
				{
						npc.Calamity().VulnerableToWater = new bool?(mob.Value);
						break;
				}
			}
			
		    //Apply sickness vulnerabilities
			foreach (var mob in thorium_npc_debuff_sickness_vulnerability) 
			{
				if ( npc.type == thorium.Find<ModNPC>(mob.Key).Type ) 
				{
						npc.Calamity().VulnerableToSickness = new bool?(mob.Value);
						break;
				}
			}
			
			//Apply electricity vulnerabilities
			foreach (var mob in thorium_npc_debuff_electricity_vulnerability) 
			{
				if ( npc.type == thorium.Find<ModNPC>(mob.Key).Type ) 
				{
						npc.Calamity().VulnerableToElectricity = new bool?(mob.Value);
						break;
				}
			}
			
			//Apply heat vulnerabilities
			foreach (var mob in thorium_npc_debuff_heat_vulnerability) 
			{
				if ( npc.type == thorium.Find<ModNPC>(mob.Key).Type ) 
				{
						npc.Calamity().VulnerableToHeat = new bool?(mob.Value);
						break;
				}
			}
		}
	}
}